<a href="https://colab.research.google.com/github/PratyushMaharana/Monty-Hall-Problem/blob/main/monty_hall_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

we are taking random choice out of 3 doors

In [ ]:
import random
doors = [0,0,0]
doors[random.randint(0,2)]=1

print(doors)

[1, 0, 0]


In [ ]:
import random

doors = [0,0,0]
doors[random.randint(0,2)]=1

print(doors)
first_choice = doors.pop(random.randint(0,2))
print(
    f"first choice door is {first_choice}.\n"
    f"remaining doors are {doors}"
)

[1, 0, 0]
first choice door is 0.
remaining doors are [1, 0]


In [ ]:
import random

doors = [0,0,0]
doors[random.randint(0,2)]=1

print(doors)
first_choice = doors.pop(random.randint(0,2))
if doors[0] == 0:
  doors.pop(0)
else:
  doors.pop(1)


[1, 0, 0]


In [ ]:
import random
repeats = 1_000_000

switch_results=[]
keep_results=[]

for _ in range(repeats):
  doors = [0,0,0]
  doors[random.randint(0,2)]=1
  first_choice = doors.pop(random.randint(0,2))
  if doors[0]==0:
    doors.pop(0)
  else:
    doors.pop(1)

  keep_results.append(first_choice)
  switch_results.append(doors[0])
print(
    f"the success rate when switching is "
    f"{sum(switch_results) / len(switch_results):.3%}"
)

print(
    f"the success rate when keeping is "
    f"{sum(keep_results) / len(keep_results):.3%}"
)

the success rate when switching is 66.668%
the success rate when switching is 33.332%


***stick this code in a function and time it using the timeit module***

In [ ]:
import random
import timeit
def solve_monty_hall_version_1():
  repeats = 1000000
  switch_results=[]
  keep_results=[]

  for _ in range(repeats):
      doors = [0,0,0]
      doors[random.randint(0,2)]=1
      first_choice = doors.pop(random.randint(0,2))
      if doors[0]==0:
         doors.pop(0)
      else:
         doors.pop(1)

      keep_results.append(first_choice)
      switch_results.append(doors[0])
  print(
      f"the success rate when switching is "
      f"{sum(switch_results) / len(switch_results):.3%}"
  )

  print(
      f"the success rate when keeping is "
      f"{sum(keep_results) / len(keep_results):.3%}"
  )
print(
    timeit.timeit(
        "solve_monty_hall_version_1()",
        globals = globals(),
        number=10,
    )
)


the success rate when switching is 66.663%
the success rate when keeping is 33.337%
the success rate when switching is 66.682%
the success rate when keeping is 33.318%
the success rate when switching is 66.641%
the success rate when keeping is 33.359%
the success rate when switching is 66.671%
the success rate when keeping is 33.329%
the success rate when switching is 66.726%
the success rate when keeping is 33.274%
the success rate when switching is 66.721%
the success rate when keeping is 33.279%
the success rate when switching is 66.728%
the success rate when keeping is 33.272%
the success rate when switching is 66.734%
the success rate when keeping is 33.266%
the success rate when switching is 66.633%
the success rate when keeping is 33.367%
the success rate when switching is 66.679%
the success rate when keeping is 33.321%
13.883508220999829


Using Numpy

start creating a 10*3 array full of 0s using np.zeroes() and replace the first column with 1's for now:

In [2]:
import numpy as np
repeats = 10
doors = np.zeros((repeats,3))
doors[:,0]=1
print(doors)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [3]:
import numpy as np
repeats = 10
doors = np.zeros((repeats,3))
doors[:,0]=1
rng=np.random.default_rng()
rng.permuted(doors,axis=1,out=doors)
doors[:,1:].sort()
print(doors)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np
repeats = 1_000_000

doors = np.zeros((repeats,3))
doors[:,0]=1

rng=np.random.default_rng()
rng.permuted(doors,axis=1,out=doors)

doors[:,1:].sort()

means=doors.mean(axis=0)

print(
    f"the success rate when switching is"
    f"{means[2]:.3%}"
)

print(
    f"the success rate when keeping is"
    f"{means[0]:.3%}"
)


the success rate when switching is66.757%
the success rate when keeping is33.243%


In [6]:
import timeit
import numpy as np
def solve_monty_hall_version_3_numpy():
    repeats = 1_000_000
    rng = np.random.default_rng()
    car_positions = rng.integers(0, 3, repeats)
    initial_choices = rng.integers(0, 3, repeats)
    switch_wins = np.mean(car_positions != initial_choices)
    keep_wins = np.mean(car_positions == initial_choices)
    print(
        f"The success rate when switching is "
        f"{switch_wins:.3%}"
    )
    print(
        f"The success rate when keeping is "
        f"{keep_wins:.3%}"
    )
print(
    timeit.timeit(
        "solve_monty_hall_version_3_numpy()",
        globals=globals(),
        number=10,
    )
)

The success rate when switching is 66.616%
The success rate when keeping is 33.384%
The success rate when switching is 66.643%
The success rate when keeping is 33.357%
The success rate when switching is 66.628%
The success rate when keeping is 33.372%
The success rate when switching is 66.589%
The success rate when keeping is 33.411%
The success rate when switching is 66.692%
The success rate when keeping is 33.308%
The success rate when switching is 66.653%
The success rate when keeping is 33.347%
The success rate when switching is 66.626%
The success rate when keeping is 33.374%
The success rate when switching is 66.681%
The success rate when keeping is 33.319%
The success rate when switching is 66.727%
The success rate when keeping is 33.273%
The success rate when switching is 66.598%
The success rate when keeping is 33.402%
0.2483210959999269
